title:             Beer Goggle Games
email:             ben.barra@sky.com
description:       Drinking Games for Every Occassion
author:            J
#url:               "localhost:4000"
url:               "http://squarezero.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
